name: Matrix

on: workflow_dispatch

jobs:
 matrix-jobs:
  runs-on: ${{matrix.os}}
  strategy:
    max-parallel: 2
    matrix:
     include:
     - index: 0
       total: 4 
       os: ubuntu-latest
     - index: 1
       os: windows-latest
     java-version: [17,21]       
  steps:
   - name: Setup Java JDK
     uses: actions/setup-java@3.14.1
     with:
      java-version: ${{matrix.java-version}}
      distribution: microsoft
